/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_cfysu_jni_JNIHello */

#ifndef _Included_com_cfysu_jni_JNIHello
#define _Included_com_cfysu_jni_JNIHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cfysu_jni_JNIHello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cfysu_jni_JNIHello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
